### ISSUE TITLE
Change date format / version for tiktok

### ISSUE THREAD

**Issue by maxpanda** [aliciawilliams/youtube-tracker#6]
Hello! Is there a way to change the date format? 

For example at the moment 23rd January is 1/23/2023

But I would like to make it 23/01/2023 instead.

Also would a tiktok implementation of this be simple?

**Comment by maxpanda** [comment]
Okay I managed to fix the Date issue, it was just a formatting thing in Google Sheets. I am wondering if there maybe a way to make a TikTok data scraper in this same fashion though.

**Comment by aliciawilliams** [comment]
It looks like you could use the [TikTok API](https://developers.tiktok.com/doc/research-api-specs-query-videos/) to do something similar, but instead of using the built-in [YouTube Service ](https://developers.google.com/apps-script/advanced/youtube) in Apps Script to source the statistics like I do in this sample, you would need to call the TikTok API using [UrlFetchApp](https://developers.google.com/apps-script/reference/url-fetch/url-fetch-app). You may be able to find examples by folks that have already done so using a web search.
